Final project proposal
npalacio/SoftwareAssurance pull request #9
Opened 2020-09-13 23:29 UTC by npalacio

2020-09-13 23:56 UTC, jburr9 requested changes
Just did a high-level overview since we already individually reviewed things. I compared our submission to the required sections in the assignment and it looks like we covered everything.

Saw a few cases of "ElasticSearch" that should be changed to "Elasticsearch" for consistency; so I'll hold until those are fixed.

Otherwise, looks great!

2020-09-14 00:19 UTC, npalacio commented
@jburr9 Fixed those ElasticSearch casing issues, updated our team reflection

2020-09-14 00:44 UTC, jburr9 approved these changes

2020-09-14 00:44 UTC, jburr9 commented
Changes look good. Great work everybody!

2020-09-14 00:44 UTC, merged